version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-data:/data
    
    command:
      # API e Dashboard
      - --api.dashboard=true
      - --api.insecure=true
      
      # Providers para Swarm
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik-public
      
      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      
      # Certificados Let's Encrypt
      - --certificatesresolvers.letsencrypt.acme.email=contato@torqueforgedmotorsport.com
      - --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      
      # Logs
      - --log.level=INFO
      - --accesslog=true
      
      # Metrics
      - --metrics.prometheus=true
    
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      labels:
        # Dashboard do Traefik
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.rule=Host(`traefik.torqueforgedmotorsport.com`)"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
        
        # Middleware de autenticação (opcional)
        - "traefik.http.middlewares.auth.basicauth.users=admin:$$2y$$10$$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi" # admin:password
        - "traefik.http.routers.dashboard.middlewares=auth"
      
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    networks:
      - traefik-public
    
    environment:
      - TRAEFIK_LOG_LEVEL=INFO

volumes:
  traefik-data:
    driver: local

networks:
  traefik-public:
    external: true