version: '3.8'

networks:
  NexiosNet:
    external: true

services:
  torque-forged:
    image: torque-forged:latest
    networks:
      - NexiosNet
    
    # Health check do Docker
    healthcheck:
      test: ["CMD", "sh", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      
      # Recursos
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      
      labels:
        # Habilitar Traefik
        - "traefik.enable=true"
        
        # Configuração de rede (IMPORTANTE)
        - "traefik.docker.network=NexiosNet"
        
        # Roteamento HTTP (redirecionamento)
        - "traefik.http.routers.torque-forged-http.rule=Host(`torqueforgedmotorsport.com`) || Host(`www.torqueforgedmotorsport.com`)"
        - "traefik.http.routers.torque-forged-http.entrypoints=web"
        - "traefik.http.routers.torque-forged-http.middlewares=redirect-to-https"
        
        # Middleware de redirecionamento HTTPS
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
        
        # Roteamento HTTPS
        - "traefik.http.routers.torque-forged-secure.rule=Host(`torqueforgedmotorsport.com`) || Host(`www.torqueforgedmotorsport.com`)"
        - "traefik.http.routers.torque-forged-secure.entrypoints=websecure"
        - "traefik.http.routers.torque-forged-secure.tls=true"
        - "traefik.http.routers.torque-forged-secure.tls.certresolver=letsencrypt"
        
        # Middleware de segurança e www redirect
        - "traefik.http.routers.torque-forged-secure.middlewares=security-headers,www-redirect"
        
        # Redirect www para não-www
        - "traefik.http.middlewares.www-redirect.redirectregex.regex=^https://www\\.(.*)"
        - "traefik.http.middlewares.www-redirect.redirectregex.replacement=https://$${1}"
        - "traefik.http.middlewares.www-redirect.redirectregex.permanent=true"
        
        # Headers de segurança
        - "traefik.http.middlewares.security-headers.headers.customRequestHeaders.X-Forwarded-Proto=https"
        - "traefik.http.middlewares.security-headers.headers.customResponseHeaders.X-Frame-Options=SAMEORIGIN"
        - "traefik.http.middlewares.security-headers.headers.customResponseHeaders.X-Content-Type-Options=nosniff"
        - "traefik.http.middlewares.security-headers.headers.customResponseHeaders.X-XSS-Protection=1; mode=block"
        - "traefik.http.middlewares.security-headers.headers.customResponseHeaders.Strict-Transport-Security=max-age=31536000; includeSubDomains"
        - "traefik.http.middlewares.security-headers.headers.customResponseHeaders.Referrer-Policy=strict-origin-when-cross-origin"
        
        # Configuração do serviço
        - "traefik.http.services.torque-forged.loadbalancer.server.port=80"
        
        # Health check do Traefik
        - "traefik.http.services.torque-forged.loadbalancer.healthcheck.path=/health"
        - "traefik.http.services.torque-forged.loadbalancer.healthcheck.interval=30s"
        - "traefik.http.services.torque-forged.loadbalancer.healthcheck.timeout=5s"